2021-10-19 at 08:41:12 | INFO | GraphQLNegativeTests.py::test_post_postalcodeinfo_ACT
2021-10-19 at 08:41:12 | INFO | POST /postalcodeinfo - Positive Test
2021-10-19 at 08:41:12 | INFO | PASSED: Test "GraphQLNegativeTests.py::test_post_postalcodeinfo_ACT" passed!
2021-10-19 at 08:41:13 | INFO | apollo_helpers.py::inner1
2021-10-19 at 08:41:13 | INFO | POST /login - Positive Test
2021-10-19 at 08:41:15 | INFO | PASSED: Test "apollo_helpers.py::inner1" passed!
2021-10-19 at 08:41:15 | INFO | apollo_helpers.py::inner1
2021-10-19 at 08:41:15 | INFO | POST /register - Positive Test
2021-10-19 at 08:41:18 | INFO | PASSED: Test "apollo_helpers.py::inner1" passed!
2021-10-19 at 08:41:18 | INFO | apollo_helpers.py::inner1
2021-10-19 at 08:41:18 | INFO | POST /register2 - Positive Test
2021-10-19 at 08:41:24 | INFO | PASSED: Test "apollo_helpers.py::inner1" passed!
2021-10-19 at 08:41:24 | INFO | apollo_helpers.py::inner1
2021-10-19 at 08:41:24 | INFO | POST /login2 - Positive Test
2021-10-19 at 08:41:24 | INFO | PASSED: Test "apollo_helpers.py::inner1" passed!
2021-10-19 at 08:41:24 | INFO | apollo_helpers.py::inner1
2021-10-19 at 08:41:24 | INFO | POST /useraccountexists - Positive Test
2021-10-19 at 08:41:25 | INFO | PASSED: Test "apollo_helpers.py::inner1" passed!
2021-10-19 at 08:41:25 | INFO | apollo_helpers.py::inner1
2021-10-19 at 08:41:25 | INFO | POST /verifyuserinvalid - Positive Test
2021-10-19 at 08:41:25 | WARNING | FAILED: Test "apollo_helpers.py::inner1" Failed with: assert ('Verification not successful. Invalid verification code provided, please try '\n 'again.') == ('Verification not successful. Invalid verification code provided, please try '\n 'again')
2021-10-19 at 08:41:26 | INFO | apollo_helpers.py::inner1
2021-10-19 at 08:41:26 | INFO | POST /verifyuserinvalid2 - Positive Test
2021-10-19 at 08:41:26 | INFO | PASSED: Test "apollo_helpers.py::inner1" passed!
2021-10-19 at 08:41:26 | INFO | apollo_helpers.py::inner1
2021-10-19 at 08:41:26 | INFO | POST /forgotpasswordinvalid - Positive Test
2021-10-19 at 08:41:27 | WARNING | FAILED: Test "apollo_helpers.py::inner1" Failed with: name 'forgotPassword' is not defined
